version: '3.8'  # 使用适合你的Docker Compose版本的版本号

services:
  # 定义后端服务
  backend:
    build: ./backend  # 后端Dockerfile所在的目录
    command: npm start  # 假设你的package.json中有一个名为"start"的脚本，它运行node server.js
    ports:
      - "3000:3000"  # 将容器的3000端口映射到宿主机的3000端口
    volumes:
      - ./backend:/app  # 将后端源代码目录挂载到容器中，便于开发时自动重启

  # 定义前端服务
  frontend:
    build: ./frontend  # 前端Dockerfile所在的目录
    command: npm run serve  # Vue CLI, Create React App等前端框架的常用命令
    ports:
      - "8080:8080"  # 将容器的8080端口映射到宿主机的8080端口，端口号根据实际情况调整
    volumes:
      - ./frontend:/app  # 将前端源代码目录挂载到容器中，便于开发时自动重启

# 如果需要，可以定义网络、卷等其他配置